# Generated by Django 5.1.4 on 2025-01-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('species', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('habitat', models.CharField(max_length=200)),
                ('is_territorial', models.BooleanField(default=False)),
                ('health', models.IntegerField(default=100)),
                ('attack_power', models.IntegerField(default=50)),
                ('defense', models.IntegerField(default=30)),
                ('speed', models.IntegerField(default=25)),
                ('primary_weakness', models.CharField(blank=True, max_length=50)),
                ('secondary_weakness', models.CharField(blank=True, max_length=50)),
                ('resistances', models.CharField(blank=True, max_length=200)),
                ('carve_rewards', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
