# Generated by Django 5.1.4 on 2025-01-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_monster_carve_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='attack_power',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='habitat',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='health',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='is_territorial',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='primary_weakness',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='resistances',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='secondary_weakness',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='speed',
        ),
    ]
