# Generated by Django 5.1.4 on 2025-01-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_monster_attack_power_remove_monster_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='monster_images/'),
        ),
    ]
