# Generated by Django 5.1.4 on 2025-01-13 20:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_monster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
    ]
