# Generated by Django 5.1.4 on 2025-03-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
